---
title: CV
name: Rachel
surname: Rhodes
phone: (805) 453-9125
email: "rachelrhodes@ucsb.edu"
github: ramrhodes
linkedin: rachelrhodes
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "Marie is a Polish and naturalized-French physicist and chemist who conducts pioneering research on radioactivity."
output: 
  vitae::markdowncv:
    theme: davewhipp
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

## Some stuff about me

 * I ran a marathon around Mont Blanc
 * I launched a small business this year
 * I am totally addicted to blueberries

## Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Master of Environmental Science and Management", "2021", "Coastal Marine Resource Management", "Bren School of Environmental Science & Management – University of California, Santa Barbara (UCSB)",
  "Bachelor of Arts", "2012", "International Relations & Environmental Studies", "Tufts University", 
  )%>% 
  detailed_entries(Degree, Year, Institution, Where)
```

## Master's Group Project

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  2020, "Marine Spatial Planning", "Spatial Prioritization to Inform Policy Recommendations for Sharks and Rays in Mozambique "
) %>% 
  brief_entries(
    glue::glue("Project in {Type}"),
    Year, 
    Desc
  )
```

## Work History

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  2020, "GIS Conservation Intern", "Wildlife Conservation Society",
  2020, "GIS Specialist", "Catalyze Inc.",
  2019, "Quality Assurance Engineer", "Catalyze Inc."
) %>% 
  brief_entries(
    glue::glue("{Type}"),
    Year, 
    Desc
  )
```